---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registrationapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registrationapi
  template:
    metadata:
      labels:
        app: registrationapi
    spec:
      containers:
        - name: registrationapi
          image: armodilo/registrationapi:v1.0.8
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: TIMESCALE_CONN_STRING
              valueFrom:
                secretKeyRef:
                  name: registrationapi-secrets
                  key: TIMESCALE_CONN_STRING
            - name: WEB_HOOK_URL
              valueFrom:
                secretKeyRef:
                  name: registrationapi-secrets
                  key: WEB_HOOK_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 150Mi
            limits:
              cpu: 400m
              memory: 300Mi

---
apiVersion: v1
kind: Service
metadata:
  name: registrationapi
spec:
  selector:
    app: registrationapi
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: autoscaling/v2 # Autoscale samo registrationapi ker se bojim hpa, ampak če rabim pokazat na predstavitvi
kind: HorizontalPodAutoscaler
metadata:
  name: registrationapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registrationapi
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
